# Generated by Django 5.0.2 on 2024-02-27 16:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerAcademicQualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
                ('major', models.CharField(blank=True, max_length=200, null=True)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('unique_identity', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_academic_qualifications_created_by', to=settings.AUTH_USER_MODEL)),
                ('job_seeker_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.jobseekerprofile')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_academic_qualifications_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_seeker_academic_qualifications',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_seeker_attachment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('file_data', models.BinaryField()),
                ('unique_identity', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_attachment_created_by', to=settings.AUTH_USER_MODEL)),
                ('job_seeker_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.jobseekerprofile')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_attachment_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_seeker_attachment',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_identity', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_contact_created_by', to=settings.AUTH_USER_MODEL)),
                ('job_seeker_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.jobseekerprofile')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_contact_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_seeker_contact',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerExperienceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_employer', models.CharField(blank=True, max_length=200, null=True)),
                ('experience_role', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('job_duties', models.CharField(blank=True, max_length=500, null=True)),
                ('implemented_projects', models.CharField(blank=True, max_length=500, null=True)),
                ('unique_identity', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_experience_certificate_created_by', to=settings.AUTH_USER_MODEL)),
                ('job_seeker_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.jobseekerprofile')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_experience_certificate_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_seeker_experience_certificate',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerProfessionalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('mark', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('is_pass', models.BooleanField(blank=True, null=True)),
                ('unique_identity', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_professional_certificate_created_by', to=settings.AUTH_USER_MODEL)),
                ('job_seeker_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.jobseekerprofile')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_professional_certificate_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_seeker_professional_certificate',
            },
        ),
    ]
