# Generated by Django 5.0.2 on 2024-02-27 16:59

import job_seeker.models.job_seeker_profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0002_jobseekeracademicqualifications_jobseekerattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=job_seeker.models.job_seeker_profile.upload_to, verbose_name='Image'),
        ),
    ]
