# Generated by Django 5.0.2 on 2024-02-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0003_jobseekerprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='birth_city',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='birth_country',
        ),
    ]
