# Generated by Django 5.0.2 on 2024-02-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0004_remove_jobseekerprofile_birth_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekeracademicqualifications',
            name='gpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
