# Generated by Django 5.0.2 on 2024-02-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0005_alter_jobseekeracademicqualifications_gpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofessionalcertificate',
            name='is_pass',
        ),
    ]
