# Generated by Django 5.0.2 on 2024-02-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0006_remove_jobseekerprofessionalcertificate_is_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerexperiencecertificate',
            name='experience_employer',
        ),
    ]
