# Generated by Django 5.0.2 on 2024-03-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0007_remove_jobseekerexperiencecertificate_experience_employer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekeracademicqualifications',
            old_name='job_seeker_identity',
            new_name='job_seeker_profile',
        ),
        migrations.RenameField(
            model_name='jobseekerattachment',
            old_name='job_seeker_identity',
            new_name='job_seeker_profile',
        ),
        migrations.RenameField(
            model_name='jobseekercontact',
            old_name='job_seeker_identity',
            new_name='job_seeker_profile',
        ),
        migrations.RenameField(
            model_name='jobseekerexperiencecertificate',
            old_name='job_seeker_identity',
            new_name='job_seeker_profile',
        ),
        migrations.RenameField(
            model_name='jobseekerprofessionalcertificate',
            old_name='job_seeker_identity',
            new_name='job_seeker_profile',
        ),
    ]
