# Generated by Django 5.0.2 on 2024-03-04 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_remove_companyjob_employment_type'),
        ('job_seeker', '0008_rename_job_seeker_identity_jobseekeracademicqualifications_job_seeker_profile_and_more'),
        ('lookup_data', '0005_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_identity', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
                ('application_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lookup_data.lookupdataapplicationstatus')),
                ('company_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.companyjob')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_application_created_by', to=settings.AUTH_USER_MODEL)),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_seeker.jobseekerprofile')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_application_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_application',
            },
        ),
    ]
