# Generated by Django 5.0.2 on 2024-04-28 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0009_jobapplication_programapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekeracademicqualifications',
            name='job_seeker_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_qualifications', to='job_seeker.jobseekerprofile'),
        ),
        migrations.AlterField(
            model_name='jobseekerattachment',
            name='job_seeker_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='job_seeker.jobseekerprofile'),
        ),
        migrations.AlterField(
            model_name='jobseekercontact',
            name='job_seeker_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='job_seeker.jobseekerprofile'),
        ),
        migrations.AlterField(
            model_name='jobseekerexperiencecertificate',
            name='job_seeker_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_certificates', to='job_seeker.jobseekerprofile'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofessionalcertificate',
            name='job_seeker_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_certificates', to='job_seeker.jobseekerprofile'),
        ),
    ]
