# Generated by Django 5.1 on 2025-03-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0010_alter_jobseekeracademicqualifications_job_seeker_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
