# Generated by Django 5.0.2 on 2024-02-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company_profile/'),
        ),
    ]
