# Generated by Django 5.0.2 on 2024-02-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companyprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company_profile_images/'),
        ),
    ]
