# Generated by Django 5.0.2 on 2024-02-23 14:57

import company.models.company_profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_companyprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=company.models.company_profile.upload_to, verbose_name='Image'),
        ),
    ]
