# Generated by Django 5.0.2 on 2024-02-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_companyimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyjob',
            name='employment_type_id',
        ),
        migrations.AddField(
            model_name='companyjob',
            name='employment_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
