# Generated by Django 5.0.2 on 2024-02-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_companyjob_employment_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyjob',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
