# Generated by Django 5.0.2 on 2024-02-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_companyjob_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyjob',
            name='salary',
            field=models.TextField(blank=True, max_length=6, null=True),
        ),
    ]
