# Generated by Django 5.0.2 on 2024-03-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_companyjob_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyimages',
            old_name='company_profile_id',
            new_name='company_profile',
        ),
    ]
