# Generated by Django 5.0.2 on 2024-03-01 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_companyimages_company_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyimages',
            name='company_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile'),
        ),
    ]
