# Generated by Django 5.0.2 on 2024-03-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_companyimages_company_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyjob',
            name='employment_type',
        ),
    ]
