# Generated by Django 5.0.2 on 2024-05-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_remove_companyjob_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyjob',
            name='salary',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
