# Generated by Django 5.0.2 on 2025-03-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_alter_companyjob_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyjob',
            old_name='end_at',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='companyjob',
            old_name='job_preferred_expertise',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='companyjob',
            name='job_required_expertise',
        ),
        migrations.RemoveField(
            model_name='companyjob',
            name='job_responsibilitie',
        ),
        migrations.RemoveField(
            model_name='companyjob',
            name='role_name',
        ),
        migrations.RemoveField(
            model_name='companyjob',
            name='start_at',
        ),
        migrations.AddField(
            model_name='companyjob',
            name='exp_level',
            field=models.CharField(choices=[('entry', 'Entry-Level'), ('intermediate', 'Intermediate'), ('senior', 'Senior')], default='entry', max_length=20),
        ),
        migrations.AddField(
            model_name='companyjob',
            name='job_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyjob',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyjob',
            name='job_type',
            field=models.CharField(choices=[('fulltime', 'Full Time'), ('parttime', 'Part Time'), ('internship', 'Internship')], default='fulltime', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyjob',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
