# Generated by Django 5.0.2 on 2025-03-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_rename_end_at_companyjob_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyjob',
            name='salary',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
