# Generated by Django 5.0.2 on 2025-03-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_alter_companyjob_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyjob',
            name='exp_level',
            field=models.CharField(choices=[('Entry-level', 'Entry-level'), ('Intermediate', 'Intermediate'), ('Senior', 'Senior')], default='Entry-level', max_length=20),
        ),
    ]
