# Generated by Django 5.1 on 2025-03-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Upcoming', max_length=10),
        ),
    ]
