# Generated by Django 5.0.2 on 2025-03-17 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_interview_status'),
        ('job_seeker', '0011_jobseekerprofile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('company_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyjob')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.jobseekerprofile')),
            ],
            options={
                'db_table': 'job_view',
            },
        ),
    ]
