# Generated by Django 5.0.2 on 2024-02-19 19:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('unique_identity', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employment_type',
            },
        ),
    ]
