# Generated by Django 5.0.2 on 2024-02-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employmenttype',
            table='lookup_employment_type',
        ),
    ]
