# Generated by Django 5.0.2 on 2024-02-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_data', '0002_alter_employmenttype_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenttype',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
