# Generated by Django 5.0.2 on 2024-03-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_data', '0003_alter_employmenttype_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmploymentType',
        ),
    ]
